sudo: required
services:
    - docker
before_install:
    - docker build -t airfork/react-test -f ./client/Dockerfile.dev ./client
script: 
    - docker run -e CI=true airfork/react-test npm test
after_sucess:
    - docker build -t airfork/multi-client ./client
    - docker build -t airfork/multi-server ./server
    - docker build -t airfork/multi-nginx ./nginx
    - docker build -t airfork/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push them to docker
    - docker push airfork/multi-client
    - docker push airfork/multi-server
    - docker push airfork/multi-nginx
    - docker push airfork/multi-worker